version: '3'

services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./bot:/bot
    ports:
      - "8000:8000"

  bot:
    build: .
    command: python /bot/main.py
    volumes:
      - ./bot:/bot
    depends_on:
      - web
