# Generated by Django 4.2.8 on 2023-12-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=8600, unique=True)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
    ]
