# Generated by Django 4.2.8 on 2024-01-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SalerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KatalogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katalog', models.CharField(choices=[("Muddatli to'lov", "Muddatli to'lov"), ('Yangi chegirmalar', 'Yangi chegirmalar'), ('Erkaklar uchun', 'Erkaklar uchun'), ('Elektronika', 'Elektronika'), ('Maishiy texnika', 'Maishiy texnika'), ('Kiyim', 'Kiyim'), ('Poyabzallar', 'Poyabzallar'), ('Aksessuarlar', 'Aksessuarlar'), ('Gozallik va parvarish', 'Gozallik va parvarish'), ('Salomatlik', 'Salomatlik'), ('Uy-rozgor buyumlari', 'Uy-ro?zg?or buyumlari'), ('Qurilish va tamirlash', 'Qurilish va ta?mirlash'), ('Avtotovarlar', 'Avtotovarlar'), ('Bolalar tovarlari', 'Bolalar tovarlari'), ('Xobbi va ijod', 'Xobbi va ijod'), ('Sport va hordiq', 'Sport va hordiq'), ('Oziq-ovqat mahsulotlari', 'Oziq-ovqat mahsulotlari'), ('Maishiy kimyoviy moddalar', 'Maishiy kimyoviy moddalar'), ('Kanselyariya tovarlari', 'Kanselyariya tovarlari'), ('Hayvonlar uchun tovarlar', 'Hayvonlar uchun tovarlar'), ('Kitoblar', 'Kitoblar'), ('Dacha, bog? va tomorqa', 'Dacha, bog? va tomorqa')], max_length=255)),
                ('category', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo1', models.ImageField(upload_to='uploads/')),
                ('photo2', models.ImageField(upload_to='uploads/')),
                ('photo3', models.ImageField(upload_to='uploads/')),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('saler_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalerApp.salerregister')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductAPP.categorymodel')),
            ],
            options={
                'verbose_name_plural': 'Markdown content',
            },
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductAPP.katalogmodel'),
        ),
    ]
