# Generated by Django 4.2.8 on 2024-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KorzinkaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mahsulot', models.IntegerField()),
                ('user_id_telegram', models.BigIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name_plural': 'Product Model'},
        ),
    ]
