# Generated by Django 4.2.8 on 2024-03-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductAPP', '0002_korzinkamodel_alter_productmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='korzinkamodel',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='korzinkamodel',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
